# Site settings
title: phackt.com:~#
tagline: "Let's talk about sec, baby!"
email: phackt[AT]protonmail.com
description: "Some infosec stuff."
baseurl: ""
url: "https://phackt.com"
paginate: 5
permalink: pretty

google_analytics_id: #UA-XXXX-Y

# Social network
twitter_username: phackt_ul
github_username:  phackt

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# highlight
highlighter: rouge
permalink: /:title

#Excluded files
#exclude:
#  - docs
#  - CNAME
#  - Gemfile
#  - Rakefile
#  - README.md
#  - .gitignore
#  - .sass-cache
#  - Gemfile.lock

# Allowing post in the future (back to the future baby)
future: true

# Syntactically Awesome Style Sheets
# sass:
#   sass_dir: public/css
#   style: :compressed

# About/contact
author:
  name: phackt
  url: https://twitter.com/phackt_ul
  email: phackt@protonmail.com

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
